### ISSUE TITLE
How to create a new room on the fly like janus api ?

### ISSUE THREAD

**Issue by ujjwal18** [OpenSight/janus-cloud#1]
its very usefull tool but there is no guide to create room dynamically.

**Comment by gushenjie** [comment]
> its very usefull tool but there is no guide to create room dynamically.

Have you realized distributed deployment of janus service through janus cloud?

**Comment by jamken** [comment]
janus-cloud try best to use the same API of janus-gateway (on Websocket）， you can use the same method with the janus-gateway.

document is not enough now, maybe you need to try and read the python code

**Comment by jamken** [comment]
> buted deployment of janus service through janus cloud?

of course, our company has provide business RTC service based on janus-cloud
