### ISSUE TITLE
Unifiedplan sdp

### ISSUE THREAD

**Issue by thevaliio** [OpenSight/janus-cloud#11]
Are you going to support the unified plan sdp? This is in the multistream branch of janus already.
Vail

**Comment by jamken** [comment]
Januscloud distribute each handle among the backend janus-servers, so the client would build the peerconnections with the different janus-servers. For videoroom, no need to support one publisher and multi subsriber streams in the same peerconnections. 
As above, unified plan sdp is not on the plan
