### ISSUE TITLE
Plugin SIP

### ISSUE THREAD

**Issue by logicall** [OpenSight/janus-cloud#15]
Hello!
Tell me, did you not consider support for the sip plugin in janus?
I am very interested in its implementation, but I don’t know python.

Thank!

**Comment by logicall** [comment]
I tried to do it myself, but something does not roll.

**Comment by jamken** [comment]
sip plugin is used for one-to-one communication which is easy to implement cluster. I recommend you can used janus-gateway directly, at the same time, implement the scability in your business server.
