### ISSUE TITLE
passphrase for certificate in janus proxy

### ISSUE THREAD

**Issue by mostafafarzane** [OpenSight/janus-cloud#2]
I added my own cert and key files in janus-proxy.yml to use "wss".
My key file needs passphrase and I added cert_pwd beside cert_pem and cert_key.

But when running janus-proxy, it asks me the passphrase.

**Comment by gushenjie** [comment]
> I added my own cert and key files in janus-proxy.yml to use "wss".
> My key file needs passphrase and I added cert_pwd beside cert_pem and cert_key.
> 
> But when running janus-proxy, it asks me the passphrase.

Have you realized distributed deployment of janus service through janus cloud?

**Comment by jamken** [comment]
maybe janus-cloud does not support this kind of cert file, perhaps you can use nginx as wss proxy to relay any http request to janus-cloud
