### ISSUE TITLE
Janus room_id in webhook is not the same

### ISSUE THREAD

**Issue by Fed0t** [OpenSight/janus-cloud#20]
Hello, 

When we create a new videoroom 
```
videoRoomHandle.create(videoRoomOptions).then((result) => {
      janusRoomId = result.room;
})
```

The result.room is different from what we receive from janus.eventhandler.sampleevh.jcfg !

It is usefull the "talking" key from participants list:
https://github.com/OpenSight/janus-cloud/wiki/VideoRoom-plugin-documentation
But in this moment it is not so useful without webhooks, because we cant make requests every second or more then one per second to get the list of participants.

Thanks!

**Comment by jamken** [comment]
// The result.room is different from what we receive from janus.eventhandler.sampleevh.jcfg !

Yes, you create a room for janus-cloud, but  janus.eventhandler send you the name of room in the jauns-gateway. 
Internally, janus-cloud would create one room of janus-gateway for each publisher, to implment the scability. So the name of the janus-cloud room is different for the name of the under-layer janus room
