### ISSUE TITLE
No 'enable_recording' api in function 'handle_message'

### ISSUE THREAD

**Issue by liqiang-xxfy** [OpenSight/janus-cloud#23]
**No 'enable_recording' api in function 'handle_message'**

https://github.com/OpenSight/janus-cloud/blob/bdecbba09d8d55114a97e7dfd1ef93ab6baf85b9/januscloud/proxy/plugin/videoroom.py#L2004-L2007

**Another bug: Replace 'enable_recording' with 'record'**

https://github.com/OpenSight/janus-cloud/blob/bdecbba09d8d55114a97e7dfd1ef93ab6baf85b9/januscloud/proxy/plugin/videoroom.py#L1107

**Comment by jamken** [comment]
Thanks, because janus-proxy API changes continuously, I would update the Januscloud API at a interval to keep consistent with it.
