### ISSUE TITLE
Unable to join a room using janus-proxy - Error Invalid element type (id should be a string)

### ISSUE THREAD

**Issue by muthuaravind** [OpenSight/janus-cloud#30]
{"videoroom":"event","error_code":430,"error":"Invalid element type (id should be a string)","traceback":[" File "/usr/local/lib/python3.6/dist-packages/januscloud/proxy/plugin/videoroom.py", line 2391, in _handle_async_message\n new_publisher.connect_backend(backend_server)\n"," File "/usr/local/lib/python3.6/dist-packages/januscloud/proxy/plugin/videoroom.py", line 786, in connect_backend\n _send_backend_message(backend_handle, body)\n"," File "/usr/local/lib/python3.6/dist-packages/januscloud/proxy/plugin/videoroom.py", line 279, in _send_backend_message\n data.get('error_code', JANUS_VIDEOROOM_ERROR_UNKNOWN_ERROR))\n"]} on session 852580733184344

**Comment by muthuaravind** [comment]
any updates on this please

**Comment by muthuaravind** [comment]
Hi @jamken

**Comment by jamken** [comment]
Hi, @muthuaravind
please provide all infomation of  this join request (with all params)

**Comment by jamken** [comment]
from your message, this error is report by the backend janus server.

**Comment by muthuaravind** [comment]
#websocket onMessage: {
       "janus": "event",
       "session_id": 852580733184344,
       "transaction": "ABP4dAvDU3wB",
       "plugindata": {
          "plugin": "janus.plugin.videoroom",
          "data": {
             "videoroom": "event",
             "error_code": 430,
             "error": "Invalid element type (id should be a string)",
             "traceback": [
                "  File \"/usr/local/lib/python3.6/dist-packages/januscloud/proxy/plugin/videoroom.py\", line 2391, in _handle_async_message\n    new_publisher.connect_backend(backend_server)\n",
                "  File \"/usr/local/lib/python3.6/dist-packages/januscloud/proxy/plugin/videoroom.py\", line 786, in connect_backend\n    _send_backend_message(backend_handle, body)\n",
                "  File \"/usr/local/lib/python3.6/dist-packages/januscloud/proxy/plugin/videoroom.py\", line 279, in _send_backend_message\n    data.get('error_code', JANUS_VIDEOROOM_ERROR_UNKNOWN_ERROR))\n"
             ]
          }
       },
       "sender": 8132604522424994
    }

**Comment by jamken** [comment]
Hi, @muthuaravind

It seams like you use the string IDs feature of the backend janus-gateway which is not supported by Janus-cloud. 
please check the configuration file of the videoroom pluagin of the backend janus-gateway, which looks like below: 

```
general: {
	#admin_key = "supersecret"		# If set, rooms can be created via API only
									# if this key is provided in the request
	#lock_rtp_forward = true		# Whether the admin_key above should be
									# enforced for RTP forwarding requests too
	#events = false					# Whether events should be sent to event
									# handlers (default=true)

	# By default, integers are used as a unique ID for both rooms and participants.
	# In case you want to use strings instead (e.g., a UUID), set string_ids to true.
	#string_ids = false            ********************** important: must set to false
}
```

**Comment by muthuaravind** [comment]
Thanks @jamken  now able to create the room
