### ISSUE TITLE
Audiobridge plugin support

### ISSUE THREAD

**Issue by Madhan-Sadasivam** [OpenSight/janus-cloud#31]
Hi, Is there any update for audiobridge plugin support ?

**Comment by Madhan-Sadasivam** [comment]
Hi @jamken, please update if we have any plan for audiobrige plugin support in janus proxy

**Comment by jamken** [comment]
no audiobrige plugin support in janus-proxy by now. But Janus-proxy is also plugable, maybe you can write this audiobrige for janus-proxy
