### ISSUE TITLE
Janus videoroom support for the audio and video file using janus-proxy

### ISSUE THREAD

**Issue by muthuaravind** [OpenSight/janus-cloud#32]
Unable to get the recorded .mjr file from the provided /opt/janus/share/janus/recordings/  path in janus-proxy.plugin.videoroom.yml and janus.plugin.videoroom.jcfg file on both config file record is set to true and rec_dir.

parameters: 

**----janus.plugin.videoroom.jcfg----**

general : 
{
  string_ids = "false";
  publishers = "8";
  bitrate = "128000";
  bitrate_cap = "true";
  request = "enable_recording";
  rec_dir = "/opt/janus/share/janus/recordings/";
  record = "true";
};

**----------------janus-proxy.plugin.videoroom.yml----** 

rooms:
    room_id: 1234
    description: "Demo Room"
    secret: "adminpwd"
    publishers: 6
    bitrate: 128000
    fir_freq: 10
    #audiocodec: "opus"
    #videocodec: "vp8"
    record: true
    rec_dir: "/opt/janus/share/janus/recordings"

**=============Error Receiving while the call connected is given below=====================**

[WARN] Unsupported combination of dir and filename  /opt/janus/share/janus/recordings/4365561421827400fm1y0nscfg@xmpp-sandbox-dev.mirrorfly.com-audio
[ERR] [record.c:janus_recorder_create_full:154] mkdir () error: 2 (No such file or directory)
[ERR] [plugins/janus_videoroom.c:janus_videoroom_recorder_create:5731] Couldn't open an audio recording file for this publisher!
[WARN] Unsupported combination of dir and filename  /opt/janus/share/janus/recordings/4365561421827400fm1y0nscfg@xmpp-sandbox-dev.mirrorfly.com-video
[ERR] [record.c:janus_recorder_create_full:154] mkdir () error: 2 (No such file or directory)
[ERR] [plugins/janus_videoroom.c:janus_videoroom_recorder_create:5760] Couldn't open an video recording file for this publisher!

@jamken kindly assist
 
Note: This setup is done after janus clustering. with 2 pods. we are able to  make calls video and voice. but failed to get the .mjr files. kindly assist

**Comment by muthuaravind** [comment]
any updates on this  team ??

**Comment by jamken** [comment]
from the error infomation, the filename, which you provice in "publish" request, contains some special char like @, which cannot be used as filename on linux.
Please give the params of  "publish" request to me.

**Comment by muthuaravind** [comment]
is the publish param will be on client side or janus server side ??  i mean on janus config file or janus-proxy yml ??

**Comment by jamken** [comment]
the publish param means the websocket reqeust(json format) which is sent by (web)client to janus-proxy.  NOT the configuration file of some server
