### ISSUE TITLE
How janus to realize the cascade, could you provide some ideas?  thank you

### ISSUE THREAD

**Issue by telinx** [OpenSight/janus-cloud#33]
Hi，
We are using Janus as a streaming server, and we want to implement the cascade of janus in the next step. 
From some articles, I know that I need to implement an rpt-forward listener.
Could you provide some idea?
Thanks.

**Comment by jamken** [comment]
no, you needn't, make janus join as the other janus's participant,  that would be a common solution(but janus-cloud doesnot support this mode, so complicated and we have no such amount of participant for one room)

**Comment by telinx** [comment]
thank you
