### ISSUE TITLE
Unable to get the recorded file!

### ISSUE THREAD

**Issue by muthuaravind** [OpenSight/janus-cloud#34]
Hi @jamken  we have done the  janus clustering proxy setup with 2 pods  running behind the proxy. when the call in initiated we have received the following error form the pod.  kindly assist.

ERROR:

**[ERR] [record.c:janus_recorder_create_full:154] mkdir () error: 2 (No such file or directory)
[ERR] [plugins/janus_videoroom.c:janus_videoroom_recorder_create:5782] Couldn't open an audio recording file for this publisher!**

**Comment by jamken** [comment]
according to the log of janus-gateway which you provide,  the reason is that the given record path does not exists on the pod host

**Comment by muthuaravind** [comment]
We have also tried by providing the directory which is inside the pod but still it ends with the above error.

**Comment by jamken** [comment]
errno =2 means     ENOENT A directory component in pathname does not exist or is a
              dangling symbolic link.


this is the error report code from record.c:janus_recorder_create_full:154
```
				/* Directory does not exist, try creating it */
				if(janus_mkdir(rec_dir, 0755) < 0) {
					JANUS_LOG(LOG_ERR, "mkdir (%s) error: %d (%s)\n", rec_dir, errno, g_strerror(errno));
					janus_recorder_destroy(rc);
					g_free(copy_for_parent);
					g_free(copy_for_base);
					return NULL;
				}
```
please check and give the directory you give to janus-gateway
