### ISSUE TITLE
Is it possible to handle multiple janus-proxy?

### ISSUE THREAD

**Issue by rikuson** [OpenSight/janus-cloud#35]
janus-cloud brought us scalable media-server.  
But is there way to make janus-proxy scalable too?

Generally, websocket can be scaled out with using Redis's pub/sub function.  
Is it possible doing like that currently?

**Comment by jamken** [comment]
multi janus-cloud is a complecated issue which means the video room status must be share and triggered by multi janus-proxy, maybe make use of zookeeper is a good idea. But now, janus-proxy solution is to make janus scalable by hold the room status by itself.

**Comment by meduar** [comment]
is there any way to implement the zookeeper? id like to do that as well

Any idea how to do it?

**Comment by jamken** [comment]
not yep.
