### ISSUE TITLE
for only one janus-gateway backend, max publishers of videoroom is only 3 (default of janus-gateway)

### ISSUE THREAD

**Issue by 04116** [OpenSight/janus-cloud#40]
https://github.com/OpenSight/janus-cloud/blob/729dcad78229c21261cee85e9a12413ceca42181/januscloud/proxy/plugin/videoroom.py#L2306

Hi @jamken,
It looks like we need to detect the number of janus-gateway, when having more than one we don't need to forward room's max publishers but for only 1, we need to do it

**Comment by jamken** [comment]
Yes, you are right. I miss setting "publishers" properties of the backend room. Thanks for your careful reminding

**Comment by cpbruno** [comment]
Why not set the number of publishers to 0, i.e., unlimited?
