### ISSUE TITLE
When is support janus-1.0.4 planned?

### ISSUE THREAD

**Issue by xujingzhou** [OpenSight/janus-cloud#41]
When is support janus-1.0.4 planned?

**Comment by jamken** [comment]
Because Janus-1.0.4 is compatible with Janus-1.0.3，so that you of course can use Janus-cloud v1.0's proxy with Janus-1.0.4 as backend server in that case the new features between Janus-1.0.3 and Janus-1.0.4 are not supported by Janus-cloud v1.0
