### ISSUE TITLE
gevent==20.9.0 does not build janus-cloud

### ISSUE THREAD

**Issue by cpbruno** [OpenSight/janus-cloud#43]
At the setup.py we see gevent being set to  `'gevent==20.9.0'` https://github.com/OpenSight/janus-cloud/blob/master/setup.py#L9

However, there is an error with gevent with Cython update: https://github.com/gevent/gevent/issues/1899

As suggested there, I could build janus-cloud with gevent 21.12.0, while 20.9.0 fails.

**Comment by hyt-hz** [comment]
gevent newer then 20.9.0 wouldn't work, please check https://github.com/OpenSight/janus-cloud/issues/47

**Comment by hyt-hz** [comment]
https://github.com/OpenSight/janus-cloud/pull/48

**Comment by hyt-hz** [comment]
https://github.com/OpenSight/janus-cloud/pull/48
