### ISSUE TITLE
Not an issue but I don't know where to ask?

### ISSUE THREAD

**Issue by thevaliio** [OpenSight/janus-cloud#5]
Can janus-cloud be clustered itself for high-availability? What if the janus-proxy "dies" during a conference?
Thank you!
Vali

**Comment by jamken** [comment]
janus-cloud is a proxy to implement janus cluster, you can make use of multi janus-cloud proxy to be handle different rooms for loadbalance, But no high-availability is design for janus-cloud proxy by now. If janus-proxy dies during a conference, the application should create another room on other janus-proxy to restart the conference rapidly. I think a video conference is not a key application which cannot be restart.

**Comment by thevaliio** [comment]
It seems we can alter jsep.sdp and add the REMB we want. Thanks!
