### ISSUE TITLE
how to use janus-sentinel.yml

### ISSUE THREAD

**Issue by gushenjie** [OpenSight/janus-cloud#7]
I have two servers with janus service installed, only server1 is started, server2 is not started, server1 and server2, server1 starts janus-proxy, and janus_server is configured, and I start janus-sentinel service on server2. Then configure post_urls, and fill in the IP address of server1. My front-end connection is the 8288 service of server1. In theory, if configured like this, it should not be forwarded to server2. But the facts will still be forwarded. Is there a problem with the configuration?

我有两台服务器，都安装了janus服务,只有server1启动了,sever2未启动,server1和server2,server1启动了janus-proxy,并且配置了janus_server,我在server2启动了janus-sentinel服务。然后配置了post_urls,里面填了server1的IP地址。我前端连接的是server1的8288服务。理论上这样配置的话,应该不会转发到server2吧。但事实还是会转发,哪里配置有问题吗？

**Comment by gushenjie** [comment]
There is another problem. If it is a distributed deployment, I need the video file. I found that it is currently generated on a different server. Is there a way for him to generate it on a designated server, I have a business here that needs to mix audio synthesis

还有一个问题,如果是分布式部署的情况下,我需要录像文件,我发现目前是在不同服务器上产生。有没有办法让他生成在一台指定服务器上,我这边有业务需要混合音频合成

**Comment by jamken** [comment]
> I have two servers with janus service installed, only server1 is started, server2 is not started, server1 and server2, server1 starts janus-proxy, and janus_server is configured, and I start janus-sentinel service on server2. Then configure post_urls, and fill in the IP address of server1. My front-end connection is the 8288 service of server1. In theory, if configured like this, it should not be forwarded to server2. But the facts will still be forwarded. Is there a problem with the configuration?
> 
> 我有两台服务器，都安装了janus服务,只有server1启动了,sever2未启动,server1和server2,server1启动了janus-proxy,并且配置了janus_server,我在server2启动了janus-sentinel服务。然后配置了post_urls,里面填了server1的IP地址。我前端连接的是server1的8288服务。理论上这样配置的话,应该不会转发到server2吧。但事实还是会转发,哪里配置有问题吗？

这个配置不是很合理，janus-sentinel和janus-gateway应该是部署在同一个节点。例如你这里准备了2台服务器，两台服务器上都应该安装janus-sentinel和janus-gateway。janus-gateway应该是由janus-sentinel来管理启动和守护的，如果server2不想启动janus-gateway那就不要启动janus-sentinel。

**Comment by jamken** [comment]
> There is another problem. If it is a distributed deployment, I need the video file. I found that it is currently generated on a different server. Is there a way for him to generate it on a designated server, I have a business here that needs to mix audio synthesis
> 
> 还有一个问题,如果是分布式部署的情况下,我需要录像文件,我发现目前是在不同服务器上产生。有没有办法让他生成在一台指定服务器上,我这边有业务需要混合音频合成

这个应用场合是通过将server1和server2挂载同一个NAS系统来实现共享。

**Comment by gushenjie** [comment]
janus-sentinel 的作用我不是太明白。我以为他会告诉janus-proxy这个服务,如果当前服务器上janus未启动,那janus-proxy那台服务器不应该去转发到未启动janus服务的服务器上了。我这个理解对吗？

**Comment by jamken** [comment]
> janus-sentinel 的作用我不是太明白。我以为他会告诉janus-proxy这个服务,如果当前服务器上janus未启动,那janus-proxy那台服务器不应该去转发到未启动janus服务的服务器上了。我这个理解对吗？

这样的理解不是很准确，janus-sentinel除了上报状态外，还负责启动本节点的janus-gateway服务，以及守护该服务（所谓守护，就是当这个服务以外崩溃后重启该服务）。janus-sentinel管理本节点的janus-gateway服务，监视它的运行状态，然后定时向janus-proxy汇报服务状态。

**Comment by gushenjie** [comment]
你说的功能我赞同。但实际我测试下来发现没有。我再复测看看
